# Wandb info
wandb_project_name: NonconvexSampling

mode: experiment
score_method: quotient-estimator

# Integrator details 
convolution_integrator: trap
integration_range: 10
dimension: 2

# Estimator Information
num_estimator_samples: 10000
eps_stable: 1e-9
gradient_estimator: conv

# Files
work_dir: training-runs/gmm-two/
ckpt_path: checkpoints/ckpt_1000.pt
samples_dir: generated_samples/

# SDE Parameters
sigma : 4

# Sampling parameters
sampling_method: em
num_samples: 10000
sampling_eps: 1e-3
disc_steps: 25

# CNF ODE Solver
atol: 1e-5
rtol: 1e-5
t1: 10
density: gmm

# Problem Specifics
density: gmm
density_parameters_path: config/density_parameters/2d_gmm.yaml
