# Wandb info
wandb_project_name: NonconvexSampling

mode: estimator-experiments
score_method: quotient-estimator

# Integrator details 
convolution_integrator: simpson
sub_intervals_per_dim: 500
integration_range: 15
dimension: 2

# Estimator Information
num_estimator_samples: 100000
eps_stable: 1e-9
gradient_estimator: conv

# SDEs Parameters
sde_type: vp
sigma_min: 0.02
sigma_max: 80
multiplier: 20
bias: 0.02

# Sampling parameters
sampling_method: em
num_batches: 20
sampling_batch_size: 500 
sampling_eps: 1e-3
disc_steps: 25

# Problem Specifics
density: gmm
density_parameters_path: config/density_parameters/2d_gmm.yaml
