mode: train

# Files
ckpt_dir: checkpoints/three/
samples_dir: samples/three/

# Training
train_iters: 1000
batch_size: 512
snapshot_freq: 250

# CNF ODE Solver
atol: 1e-5
rtol: 1e-5
t1: 10

# Optimizer
optimizer: Adam
lr: 1e-3

# Problem Specifics
density: gmm
coeffs: [.33, .33, .34]
means: [-5, 5, 10]
variances: [1, 1, 1]