# Wandb info
wandb_project_name: NonconvexSampling

mode: experiment
score_method: quotient-estimator

# Integrator details 
convolution_integrator: simpson
sub_intervals: 1000
integration_range: 15
dimension: 1

# Estimator Information
num_estimator_samples: 15000
eps_stable: 1e-9
gradient_estimator: conv

# SDEs Parameters
sde_type: ve
sigma_min: 0.02
sigma_max: 80
multiplier: 20
bias: 0.02


# Sampling parameters
sampling_method: em
num_samples: 10000
sampling_eps: 1e-3
disc_steps: 25

# Problem Specifics
density: gmm
density_parameters_path: config/density_parameters/1d_gmm.yaml