mode: train

# Files
work_dir: training-runs/gmm-two/
ckpt_dir: checkpoints/
samples_dir: samples/

# Training
train_iters: 1000
batch_size: 512
snapshot_freq: 250
num_eval_samples: 10000

# CNF ODE Solver
atol: 1e-5
rtol: 1e-5
t1: 10

# Optimizer
optimizer: Adam
lr: 1e-3

# Problem Specifics
density: gmm
coeffs: [.5, .5]
means: [-5, 5]
variances: [2, 2]